name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create Gradle Wrapper
      run: |
        # 创建 Gradle Wrapper
        gradle wrapper --gradle-version 8.0
        chmod +x ./gradlew
        
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: iptv-app
        path: app/build/outputs/apk/debug/*.apk