name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create and use Gradle 8.0 Wrapper
      run: |
        # 删除可能存在的旧 wrapper
        rm -f gradlew
        rm -rf gradle/wrapper/
        
        # 创建目录结构
        mkdir -p gradle/wrapper/
        
        # 手动创建 gradle-wrapper.properties
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF
        
        # 下载预编译的 gradlew 脚本
        curl -o gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradlew
        chmod +x ./gradlew
        
        # 验证使用的 Gradle 版本
        ./gradlew --version
      
    - name: Build APK
      run: ./gradlew assembleDebug --no-daemon
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: iptv-app
        path: app/build/outputs/apk/debug/*.apk